version: "2.0"
recipe: "default.v1"
language: vi
pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    constrain_similarities: true
    entity_recognition: false
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.7
# - name: "WhitespaceTokenizer"
  # - name: "VietnameseTokenizer"
# - name: "CountVectorsFeaturizer"
# - name: "DIETClassifier"
# - name: "CRFEntityExtractor"
  # - name: "EntitySynonymMapper"
  # - name: WhitespaceTokenizer
  # - name: LexicalSyntacticFeaturizer
  # - name: CRFEntityExtractor
  # - name: RegexEntityExtractor
  # - name: DIETClassifier

  # - name: WhitespaceTokenizer
  # - name: LexicalSyntacticFeaturizer
  # - name: CountVectorsFeaturizer
  # - name: RegexEntityExtractor
  # - name: DIETClassifier
    # entity_recognition: true
  # - name: FallbackClassifier
  #   threshold: 0.7
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  constrain_similarities: true
  max_history: 5
  epochs: 100
- name: RulePolicy

model:
  name: admission
assistant_id: 20230721-171547-grandioso-diffraction
