language: vi
pipeline:
  - name: WhitespaceTokenizer
  # - name: LexicalSyntacticFeaturizer
  # - name: CRFEntityExtractor
  - name: RegexEntityExtractor
    case_sensitive: false
    use_lookup_tables: true
    use_regexes: false
    use_word_boundaries: true
  - name: DIETClassifier
    constrain_similarities: true
 
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 5
  - name: RulePolicy
assistant_id: 20230412-111502-few-tower

# models:
#   path: "models"
#   model_name: "nlu_admission_informations"