language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    entity_recognition: false
    epochs: 100
  - name: RegexEntityExtractor
    use_lookup_tables: true
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
assistant_id: 20230412-111502-few-tower

models:
  - name: "20230419-014716-grim-outrigger"
    language: "en"
    path: "models/20230419/20230419-014716-grim-outrigger"
