language: vi
pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: RegexEntityExtractor
    case_sensitive: true
    use_lookup_tables: true
    use_regexes: true
    use_word_boundaries: true
  - name: DIETClassifier
    entity_recognition: true
  - name: FallbackClassifier
    threshold: 0.7
 
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 3
  - name: RulePolicy
assistant_id: 20230412-111502-few-tower
